//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_Task
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genere
    {
        public int Id { get; set; }
        public string Genere1 { get; set; }
    }
}
